### ISSUE TITLE
Invalid Argument

### ISSUE THREAD

**Issue by elvispdosreis** [silexlabs/amfphp-2.0#20]
Flex
public function getAmf(metodo:String, result:Function):void{
  var op:Operation = bridge.getOperation(metodo) as Operation;
   var async:AsyncToken = op.send();
   async.addResponder(new Responder(result, defaultFaultHandler));
}

php

public function menu(){
}

return error
Invalid number of parameters for method menu in service IMP.Ipm : 0  required, 0 total, 1 provided

**Comment by arielsom** [comment]
you need a parameter for your function. Try this
php

public function menu($parameter){

}

and if you want to return something(here your parameter * 2):
public function menu($parameter){
  return $parameter * 2;
}

**Comment by elvispdosreis** [comment]
My functions that have parameters function normally, the problem only occurs in functions without parameters.

**Comment by arielsom** [comment]
Likely you are indeed sending a parameter, but just from your code I can't tell why. Have you tried the Backoffice's client generator? It should give you some clean client code you can play with.
http://www.silexlabs.org/amfphp/documentation/using-the-back-office/client-generator/ 
Otherwise have a look at what's going over the network.
http://www.silexlabs.org/amfphp/documentation/using-a-packet-sniffer/
